version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: nocturna-umbrel-mount-network_app_1
      APP_PORT: "8189"
      
  app:
    image: alpine:3.20
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - /home/umbrel/umbrel/network:/mnt/network
      - ./start.sh:/start.sh
    entrypoint: ["/bin/sh", "/start.sh"]
