version: "3.7"
services:
  mount-network:
    image: alpine:3.20
    container_name: nocturna-mount-network
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - /home/umbrel/umbrel/network:/mnt/network
    command: >
      sh -c "
      echo "works"
      "
    cap_add:
      - SYS_ADMIN
