version: "3.7"
services:
  mount-network:
    image: alpine:3.20
    container_name: nocturna-mount-network
    restart: unless-stopped
    environment:
      - MOUNT_SERVER=${MOUNT_SERVER:-192.168.111.1}
      - MOUNT_SHARE=${MOUNT_SHARE:-Fritzbox-Fynn-NAS}
      - MOUNT_USER=${MOUNT_USER:-Username}
      - MOUNT_PASS=${MOUNT_PASS:-Password}
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - /home/umbrel/umbrel/network:/mnt/network
    command: >
      sh -c "
      mkdir -p /mnt/network/\${MOUNT_SERVER}/\${MOUNT_SHARE} &&
      mount -t cifs -o rw,vers=3.0,noserverino,username=\${MOUNT_USER},password=\${MOUNT_PASS} //\${MOUNT_SERVER}/\${MOUNT_SHARE} /mnt/network/\${MOUNT_SERVER}/\${MOUNT_SHARE} &&
      tail -f /dev/null
      "
    cap_add:
      - SYS_ADMIN
